.TH cs-console 1
.SH NAME
cs-console \- connect user's terminal to a XINU backend console
.SH SYNOPSIS
.B cs-console
[
.BR \-h
]
[
.BR \-t
]
[
.BR \-f
]
[
.BI \-c " class"
]
[
.BI \-s " server"
]
[
.BI connection
]
.SH DESCRIPTION
.I Cs-console
connects a terminal on the frontend unix box 
to a XINU backend console line such that the output
of the backend appears on the terminal screen and characters
typed at the 
keyboard are sent to the backend.
\f2Cs-console\f1 sets the backend's tty line to raw mode, and the unix
box terminal to 
cbreak mode.  Under normal conditions, \f2Cs-console\f1 interracts with
the monitor program on the XINU backends.
The connection can be closed by escaping to the monitor, (CONTROL-@,
or CONTROL-Spacebar, depending on your terminal,)
and choosing the "q" option for "quit".
.PP
The monitor contains commands for downloading kernels to the backend, 
powercycling the backend, or sending a break character to the backend.
.PP
Options are:
.TP
.BI \-c " class"
Class. Connect to a machine in the class
.I class
if one is available.  The default class is i586.
The value of
.I class
can also be set using the environment
variable "CS_CLASS".
.TP
.BI \-s " server"
Server. Uses the hostname or IP address
.I server
to communicate with the backend console terminal server daemon.
(Also called the "cserver" daemon.)  By default,
\f2cs-console\f1 will send out a broadcast request for the proper
server on the current subnet.  This parameter should only be set if
selecting between several available servers, or connecting to a server
on another subnet.  The value of
.I server
can also be set using the colon-delimited environment variable
"CS_SERVERS".
.TP
.BI \-h
Help.  Prints a short usage blurb.
.TP
.TP
.BI \-t 
Transparent mode.
Don't use this if you don't already know what it is for.
.TP
.BI \-f
Flush timeout.
Deprecated under modern versions of \f2cs-console\f1.
.SH "SEE ALSO"
cs-status(1)
.SH BUGS
On some systems, network broadcast search for cserver daemons will
fail if the environment variable CS_SERVERS is set to a broadcast
address, like "128.10.3.255".
.SH HISTORY
The exact lineage of
.B cs-console
is forever lost in the sands of time.
The original ancestor of
.B cs-console
was called \f2odt\f1.  Believed to have first appeared circa 1978,
\f2odt\f1 was named for the "Octal Debugging Tool" that standard
DEC machines of that era had as the equivalent to modern boot PROMs.
Original culprits for the XINU \f2odt\f1 tool were probably Bob Brown
and Doug Comer.  Across the decades, this tool has appeared in many
incarnations, allowing a wide variety of frontend architectures to 
connect to a wide variety of backend consoles.

The current incarnation (v2.0) has been dusted off and ported to
Linux by Dennis Brylow and Chris Telfer.
