#!/bin/sh

PATH="/bin:/usr/bin:/usr/ucb"

configdir=/p/srg/etc/conconfig

contoolsdir=/p/srg/etc/contools

if [ ! -d $configdir ]
then
  exit 0
fi

#
# find them
#
TEMP=/tmp/.murder.$$

pattern="$contoolsdir/.*$"

if [ -f /usr/local/bin/bintype ]
then
  bt=`/usr/local/bin/bintype -os`
else
  bt=unknown
fi

pids=

case $bt in
  *-sos5)   ps -ef | grep -v $0 | egrep "[^:]*:[0-9][0-9] $pattern" > $TEMP
	    pids=`cat $TEMP | sed -e 's/^[ ]*[^ ]*  *\([0-9]*\).*$/\1/g'`
	    ;;
  *-sos4|*) ps agxwww | grep -v $0 | egrep "[^:]*:[0-9][0-9] $pattern" > $TEMP
	    pids=`cat $TEMP | sed -e 's/^[ ]*\([0-9]*\).*$/\1/g'`
	    ;;
esac

if [ "$pids" != "" ]
then
  kill -INT $pids
  sleep 2
fi

rm -f $TEMP

#
# start connection server
#
cserver=$contoolsdir/cserver

if [ -f $cserver ]
then
  $cserver
fi

exit 0

