#!/bin/sh

PATH="/bin:/usr/bin:/usr/ucb"

contoolsdir=/p/srg/etc/contools

tconnect=$contoolsdir/telnet-connect

if [ $# -ne 2 ]
then
  echo "usage:$0 host port"
  exit 1
fi

#
# find them
#
TEMP=/tmp/.murder.$$

pattern="$tconnect -f $1 $2$"

if [ -f /usr/local/bin/bintype ]
then
  bt=`/usr/local/bin/bintype -os`
else
  bt=unknown
fi

pids=

case $bt in
  *-sos5) ps -ef | grep -v $0 | egrep "[^:]*:[0-9][0-9] $pattern" > $TEMP
	  pids=`cat $TEMP | sed -e 's/^[ ]*[^ ]*  *\([0-9]*\).*$/\1/g'`
	  ;;
  *-sos4|*) ps agxwww | grep -v $0 | egrep "[^:]*:[0-9][0-9] $pattern" > $TEMP
	    pids=`cat $TEMP | sed -e 's/^[ ]*\([0-9]*\).*$/\1/g'`
	    ;;
esac

if [ "$pids" = "" ]
then
  $tconnect -b $1 $2
else
  kill -USR1 $pids
fi

rm -f $TEMP

exit 0
